- name: Example PlayBook Level ## {list types variable}
  hosts: all
  become: true
  vars:
         mypkg:
         - httpd
         - vsftpd
         - wget
  tasks:
       - name: install web services
         yum: 
            name: "{{mypkg}}"
            state: installed
